"use client";
import { useState } from "react";
import { Download, MapPin, RefreshCw } from "lucide-react";
import { refreshGBP } from "@/lib/api";
import type { LocalSEOSnapshot } from "@/types/api";
const tabs = ["Overview", "Business Profile", "Locations", "NAP", "Reviews", "Local Rankings", "Local Queries", "Landing Pages", "Citations", "Competitors", "Opportunities", "History"];
function download(name: string, rows: Record<string, unknown>[]) { if (!rows.length) return; const keys = Object.keys(rows[0]); const cell = (value: unknown) => { const text = String(value ?? ""); const safe = /^[=+\-@]/.test(text) ? `'${text}` : text; return `"${safe.replaceAll('"', '""')}"`; }; const body = [keys.map(cell).join(","), ...rows.map((row) => keys.map((key) => cell(row[key])).join(","))].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([body], { type: "text/csv" })); link.download = name; link.click(); URL.revokeObjectURL(link.href); }
function Data({ title, rows }: { title: string; rows: Record<string, unknown>[] }) { const keys = rows.length ? Object.keys(rows[0]).slice(0, 8) : []; return <>{<div className="panel-heading"><h2>{title}</h2><button className="text-button" disabled={!rows.length} onClick={() => download(`local_${title.toLowerCase().replaceAll(" ", "_")}.csv`, rows)}><Download size={14}/>CSV</button></div>}{rows.length ? <div className="data-table-wrap"><table><caption className="sr-only">{title}</caption><thead><tr>{keys.map((key) => <th key={key}>{key.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{rows.slice(0, 100).map((row, index) => <tr key={index}>{keys.map((key) => <td key={key}>{typeof row[key] === "object" ? JSON.stringify(row[key]) : String(row[key] ?? "N/A")}</td>)}</tr>)}</tbody></table></div> : <div className="empty-inline">No persisted {title.toLowerCase()} evidence is available.</div>}</>; }
export function LocalSEOWorkspace({ initial }: { initial: LocalSEOSnapshot }) { const [tab, setTab] = useState("Overview"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [gbpStatus, setGbpStatus] = useState(""); const data = initial.data; const map: Record<string, Record<string, unknown>[]> = { "Business Profile": data.locations.filter((item) => item.provider === "GOOGLE_BUSINESS_PROFILE"), Locations: data.locations, NAP: data.nap_assessments, Reviews: [...data.reviews, ...data.review_summaries], "Local Rankings": data.ranks, "Local Queries": data.queries, "Landing Pages": data.landing_pages, Citations: data.citations, Competitors: data.competitors, Opportunities: data.opportunities, History: data.history }; async function refresh() { setBusy(true); setError(""); try { const result = await refreshGBP() as { status?: string }; if (result.status && result.status !== "REFRESHED") setGbpStatus(result.status); else location.reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : "GBP refresh failed."); } finally { setBusy(false); } } return <><section className="panel module-panel"><div className="panel-heading"><div><h2>Google Business Profile · read only</h2><p>Profile data refreshes only through this explicit action.</p></div><button className="primary-button" disabled={!initial.gbp_configured || busy} onClick={refresh}><RefreshCw size={14}/>{busy ? "Refreshing…" : "Refresh GBP profile"}</button></div>{!initial.gbp_configured ? <div className="empty-inline">GBP OAuth configuration is missing. Persisted Local SEO intelligence remains available.</div> : null}{gbpStatus ? <div className="error-state" role="status">GBP status: {gbpStatus}</div> : null}</section>{error ? <div className="error-state" role="alert">{error}</div> : null}<div className="module-tabs" role="tablist">{tabs.map((item) => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? "selected" : ""} onClick={() => setTab(item)}>{item}</button>)}</div><section className="panel module-panel">{tab === "Overview" ? <div className="empty-state"><MapPin/><strong>Evidence-backed local intelligence</strong><p>Unavailable signals remain N/A. Nexora does not claim Google ranking causality.</p></div> : <Data title={tab} rows={map[tab] ?? []}/>}</section></>; }
