"use client";
import { FormEvent, useState } from "react";
import { Download, Upload } from "lucide-react";
import { importPaidMedia } from "@/lib/api";
export function PaidMediaWorkspace({ platform, initial }: { platform: "google-ads" | "meta-ads"; initial: Record<string, unknown>[] }) {
 const [result, setResult] = useState<Record<string, unknown> | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false);
 async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); try { const campaigns = JSON.parse(String(f.get("campaigns"))); const account = platform === "google-ads" ? { customer_id: f.get("account"), currency_code: String(f.get("currency")).toUpperCase() } : { ad_account_id: f.get("account"), currency: String(f.get("currency")).toUpperCase() }; const imported = await importPaidMedia(platform, { account, period: { date_from: f.get("start"), date_to: f.get("end") }, campaigns, source: "IMPORT" }); setResult(imported as Record<string, unknown>); setError(""); } catch (x) { setError(x instanceof Error ? x.message : "Import could not be analyzed."); } finally { setBusy(false); } }
 const audit = result && typeof result.audit === "object" ? result.audit as Record<string, unknown> : initial[0], rows = audit && Array.isArray(audit.campaigns) ? audit.campaigns as Record<string, unknown>[] : [];
 function csv() { if (!rows.length) return; const keys = Object.keys(rows[0]), cell = (value: unknown) => { const text = String(value ?? ""), safe = /^[=+\-@]/.test(text) ? `'${text}` : text; return `"${safe.replaceAll('"', '""')}"`; }, body = [keys.map(cell).join(","), ...rows.map(r => keys.map(k => cell(r[k])).join(","))].join("\n"), link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([body], { type: "text/csv" })); link.download = `nexora_${platform}_campaigns.csv`; link.click(); URL.revokeObjectURL(link.href); }
 return <><section className="panel module-panel"><div className="panel-heading"><div><h2>Imported campaign analysis</h2><p>Live ad connectivity and campaign mutations are unavailable.</p></div><span className="status-badge">IMPORT MODE</span></div><form className="crawl-form" onSubmit={submit}><label><span>{platform === "google-ads" ? "Customer ID" : "Ad account ID"}</span><input name="account" required /></label><label><span>Currency</span><input name="currency" defaultValue="INR" required /></label><label><span>Period start</span><input name="start" type="date" required /></label><label><span>Period end</span><input name="end" type="date" required /></label><label className="wide-field"><span>Campaign JSON array</span><textarea name="campaigns" required placeholder='[{"campaign_id":"1","name":"Search"}]' /></label><button className="primary-button" disabled={busy}><Upload size={14} />{busy ? "Analyzing…" : "Analyze imported data"}</button></form></section>{error ? <div className="error-state" role="alert">{error}</div> : null}<section className="panel module-panel"><div className="panel-heading"><h2>Campaign performance</h2><button className="text-button" disabled={!rows.length} onClick={csv}><Download size={14} />CSV</button></div>{rows.length ? <div className="data-table-wrap"><table><caption className="sr-only">Imported campaign performance</caption><thead><tr>{Object.keys(rows[0]).slice(0, 10).map(k => <th key={k}>{k.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i}>{Object.keys(rows[0]).slice(0, 10).map(k => <td key={k}>{String(r[k] ?? "N/A")}</td>)}</tr>)}</tbody></table></div> : <div className="empty-inline">No imported campaign audit is persisted yet.</div>}</section></>;
}
