"use client";

import { FormEvent, useRef, useState, useTransition } from "react";
import { Download, Plus, Radar, RefreshCw, Search } from "lucide-react";
import { useRouter } from "next/navigation";

import { addTrackedKeyword, checkRanks, getRankHistory } from "@/lib/api";
import type { RankCheck, RankTrackingSnapshot } from "@/types/api";

function downloadCsv(name: string, rows: Array<Record<string, unknown>>) {
  if (!rows.length) return;
  const columns = Object.keys(rows[0]);
  const cell = (value: unknown) => { const text = String(value ?? ""); const safe = /^[=+\-@]/.test(text) ? `'${text}` : text; return `"${safe.replaceAll('"', '""')}"`; };
  const csv = [columns.map(cell).join(","), ...rows.map((row) => columns.map((key) => cell(row[key])).join(","))].join("\n");
  const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = name; link.click(); URL.revokeObjectURL(link.href);
}

export function RankTrackingWorkspace({ initial }: { initial: RankTrackingSnapshot | null }) {
  const router = useRouter(); const [pending, startTransition] = useTransition();
  const [tab, setTab] = useState("rankings"); const [error, setError] = useState(""); const [depth, setDepth] = useState(20); const [selected, setSelected] = useState(""); const [history, setHistory] = useState<RankCheck[]>([]); const [submitting, setSubmitting] = useState(false); const selectionSequence = useRef(0);
  const rows = initial?.rows ?? [];
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (submitting) return; setSubmitting(true); setError(""); const form = new FormData(event.currentTarget); try { await addTrackedKeyword({ keyword: String(form.get("keyword")), target_domain: String(form.get("target")), target_url: String(form.get("targetUrl") || "") || undefined, country: String(form.get("country")), device: String(form.get("device")) }); event.currentTarget.reset(); startTransition(() => router.refresh()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Keyword could not be added."); } finally { setSubmitting(false); } }
  async function check() { if (submitting) return; setSubmitting(true); setError(""); try { await checkRanks(depth); startTransition(() => router.refresh()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Rank check failed."); } finally { setSubmitting(false); } }
  async function selectHistory(id: string) { const sequence = ++selectionSequence.current; setSelected(id); setHistory([]); setError(""); try { const result = id ? await getRankHistory(id) : []; if (sequence === selectionSequence.current) setHistory(result); } catch (reason) { if (sequence === selectionSequence.current) setError(reason instanceof Error ? reason.message : "History could not be loaded."); } }
  return <>
    <section className="panel module-panel"><div className="panel-heading"><div><span className="eyebrow">Tracked context</span><h2>Add keyword</h2></div><Plus size={19}/></div><form className="rank-form" onSubmit={add}><label><span>Keyword</span><input name="keyword" required maxLength={256}/></label><label><span>Target domain</span><input name="target" required maxLength={253}/></label><label><span>Target URL (optional)</span><input name="targetUrl" type="url" maxLength={2048}/></label><label><span>Country</span><select name="country"><option>US</option><option>IN</option><option>GB</option><option>AU</option></select></label><label><span>Device</span><select name="device"><option value="desktop">Desktop</option><option value="mobile">Mobile</option></select></label><button className="primary-button" disabled={pending}><Plus size={15}/> Add keyword</button></form></section>
    <section className="panel module-panel action-strip"><div><strong>Explicit live rank check</strong><p>{initial?.configured ? "Serper is configured. No request occurs until you start a check." : "SERPER_API_KEY is missing. Persisted rankings remain available."}</p></div><label><span>Depth</span><select value={depth} onChange={(event)=>setDepth(Number(event.target.value))}><option>10</option><option>20</option><option>50</option></select></label><button className="primary-button" disabled={!initial?.configured || pending} onClick={check}><RefreshCw size={15}/> {pending ? "Checking…" : "Check ranks"}</button></section>
    {error ? <div className="error-state" role="alert">{error}</div> : null}
    <div className="module-tabs" role="tablist">{[["rankings","Current rankings"],["history","Rank history"],["serp","SERP snapshot"],["competitors","Competitors"],["changes","Winners / losers"]].map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?"selected":""} onClick={()=>setTab(key)}>{label}</button>)}</div>
    <section className="panel module-panel">
      {tab==="rankings" && <><div className="panel-heading"><h2>Tracked keywords</h2><button className="text-button" onClick={()=>downloadCsv("nexora_current_rankings.csv",rows.map(row=>({keyword:row.keyword.keyword,target:row.keyword.target_url??row.keyword.target_domain,country:row.keyword.context.country,device:row.keyword.context.device,engine:row.keyword.context.search_engine,position:row.latest_check?.target_position??"NOT AVAILABLE",change:row.change?.change_type??"NOT AVAILABLE",provider:row.latest_check?.provider??"NOT AVAILABLE",source:row.latest_check?.source??"NOT AVAILABLE"})))}><Download size={14}/> CSV</button></div>{rows.length?<div className="data-table-wrap"><table><caption className="sr-only">Current tracked keyword rankings</caption><thead><tr><th>Keyword</th><th>Target</th><th>Context</th><th>Observed position</th><th>Change</th><th>GSC position</th><th>Provider</th></tr></thead><tbody>{rows.map(row=><tr key={row.keyword.keyword_id}><td><strong>{row.keyword.keyword}</strong></td><td>{row.keyword.target_url??row.keyword.target_domain}</td><td>{row.keyword.context.country} · {row.keyword.context.device} · {row.keyword.context.search_engine}</td><td>{row.latest_check?.target_position??(row.latest_check?`NOT FOUND TOP ${row.latest_check.depth}`:"NOT AVAILABLE")}</td><td>{row.change?.change_type??"NOT AVAILABLE"}</td><td>{row.keyword.gsc_average_position??"N/A"}</td><td>{row.latest_check?.provider??"N/A"}</td></tr>)}</tbody></table></div>:<div className="empty-state"><Search size={22}/><strong>No tracked keywords</strong><p>Add a keyword above. This does not run a provider check.</p></div>}</>}
      {tab==="history" && <><div className="panel-heading"><h2>Observed rank history</h2><select aria-label="Tracked keyword" value={selected} onChange={(e)=>selectHistory(e.target.value)}><option value="">Select keyword</option>{rows.map(row=><option key={row.keyword.keyword_id} value={row.keyword.keyword_id}>{row.keyword.keyword}</option>)}</select></div>{history.length?<div className="data-table-wrap"><table><caption className="sr-only">Rank history</caption><thead><tr><th>Checked</th><th>Position</th><th>Depth</th><th>Provider</th><th>Source</th></tr></thead><tbody>{history.map(item=><tr key={item.check_id}><td>{new Date(item.checked_at).toLocaleString()}</td><td>{item.target_position??`NOT FOUND TOP ${item.depth}`}</td><td>{item.depth}</td><td>{item.provider}</td><td>{item.source}</td></tr>)}</tbody></table></div>:<div className="empty-state"><Radar size={22}/><strong>No persisted rank observations are available yet.</strong><p>Select a keyword with completed explicit checks.</p></div>}</>}
      {tab==="serp" && <>{rows.some(r=>r.latest_check?.results.length)?<div className="data-table-wrap"><table><caption className="sr-only">Latest SERP results</caption><thead><tr><th>Keyword</th><th>Position</th><th>Domain</th><th>Title</th><th>Type</th></tr></thead><tbody>{rows.flatMap(row=>(row.latest_check?.results??[]).map(result=><tr key={`${row.keyword.keyword_id}-${result.position}`}><td>{row.keyword.keyword}</td><td>{result.position}</td><td>{result.domain}</td><td>{result.title}</td><td>{result.result_type}</td></tr>))}</tbody></table></div>:<div className="empty-state"><Radar size={22}/><strong>No captured SERP snapshot</strong><p>Run an explicit configured check first.</p></div>}</>}
      {tab==="competitors" && <>{initial?.competitors.length?<div className="data-table-wrap"><table><caption className="sr-only">Competitor SERP observations</caption><thead><tr><th>Domain</th><th>Keywords</th><th>Top 3</th><th>Top 10</th><th>Average position</th><th>Best</th></tr></thead><tbody>{initial.competitors.map(item=><tr key={item.domain}><td><strong>{item.domain}</strong></td><td>{item.keywords_observed}</td><td>{item.top_3_appearances}</td><td>{item.top_10_appearances}</td><td>{Number(item.average_observed_position).toFixed(1)}</td><td>{item.best_observed_position}</td></tr>)}</tbody></table></div>:<div className="empty-state"><Radar size={22}/><strong>No competitor observations</strong><p>Competitors are derived only from persisted SERP results.</p></div>}</>}
      {tab==="changes" && <>{rows.filter(r=>r.change&&!['BASELINE','STABLE'].includes(r.change.change_type)).length?<div className="data-table-wrap"><table><caption className="sr-only">Ranking winners and losers</caption><thead><tr><th>Keyword</th><th>State</th><th>Previous</th><th>Current</th><th>Movement</th></tr></thead><tbody>{rows.filter(r=>r.change&&!['BASELINE','STABLE'].includes(r.change.change_type)).map(row=><tr key={row.keyword.keyword_id}><td>{row.keyword.keyword}</td><td>{row.change?.change_type}</td><td>{row.change?.previous_position??"N/A"}</td><td>{row.change?.current_position??"N/A"}</td><td>{row.change?.movement??"N/A"}</td></tr>)}</tbody></table></div>:<div className="empty-state"><Radar size={22}/><strong>No winners or losers yet</strong><p>At least two compatible observations are required.</p></div>}</>}
    </section>
  </>;
}
