from __future__ import annotations
import asyncio
import pandas as pd
import streamlit as st
from dashboard.ai_visibility_workflow import AIVisibilityDashboardWorkflow
from src.ai_visibility.domain import VisibilityReport,VisibilityRequest
from src.ai_visibility.citation_intelligence import CitationIntelligenceService
def run(c):return asyncio.run(c)
def observations_frame(r):return pd.DataFrame([{"Prompt":o.prompt,"Category":o.category.value,"Provider":o.provider,"Model":o.model,"Brand mentioned":o.brand_mention is not None if o.state.value=="SUCCESS" else None,"Mention count":o.brand_mention.count if o.brand_mention else 0,"Target cited":o.target_domain_cited,"Competitors mentioned":", ".join(m.name for m in o.competitor_mentions),"Sources":", ".join(c.url for c in o.citations),"Observation state":o.state.value,"Observed at":o.observed_at} for o in r.run.observations])
def markdown(r):return "# Nexora AI Visibility Report\n\n"+f"- Brand: {r.run.brand_name}\n- Target domain: {r.run.target_domain}\n- Prompts: {r.run.prompt_count}\n- Repetitions: {r.run.repetitions}\n- Observed brand mention coverage: {r.brand_mention_coverage:.1%}\n- Citation coverage: {f'{r.citation_coverage:.1%}' if r.citation_coverage is not None else 'NOT AVAILABLE'}\n\n## Actions\n"+"\n".join(f"- {x}" for x in r.actions)+"\n\n## Limitations\n"+"\n".join(f"- {x}" for x in r.limitations)+"\n"
def grounded_markdown(coverage,sources,pages,actions):return "# Grounded AI Citation Report\n\n## Monitoring scope\nProvider-specific structured citations only.\n\n## Target citation coverage\n"+f"{coverage.numerator}/{coverage.denominator} ({f'{coverage.coverage:.1%}' if coverage.coverage is not None else 'NOT AVAILABLE'})\n\n## Top target URLs\n"+"\n".join(f"- {p.target_url}: {p.citation_count}" for p in pages)+"\n\n## Top source domains\n"+"\n".join(f"- {s.domain}: {s.citation_count}" for s in sources)+"\n\n## AEO/GEO comparison\nReadiness does not guarantee observed citation.\n\n## Actions\n"+"\n".join(f"- {x}" for x in actions)+"\n\n## Limitations\nFailed and ungrounded observations are excluded. No citation causality or AI ranking is claimed.\n"
def render_grounded(history,workflow=None,target_domain=""):
 service=CitationIntelligenceService();capable=service.successful_capable(history);coverage=service.target_coverage(history);citations=[c for o in capable for c in o.citations];target_urls=sorted({c.normalized_url or c.url for c in citations if c.is_target});competitors=sorted({c.competitor for c in citations if c.competitor});sources=service.source_domains(history)
 st.subheader("Grounded citation intelligence");st.write("Only provider-supplied structured source metadata is counted. Ordinary prose URLs and ungrounded model responses are excluded.")
 with st.container(horizontal=True):st.metric("Citation-capable prompts",coverage.denominator,border=True);st.metric("Target citation coverage",f"{coverage.coverage:.1%}" if coverage.coverage is not None else "NOT AVAILABLE",border=True);st.metric("Target URLs cited",len(target_urls),border=True);st.metric("Competitor domains cited",len(competitors),border=True);st.metric("Source domains observed",len(sources),border=True)
 prompts=pd.DataFrame([{"Prompt":o.prompt,"Provider":o.provider,"Model":o.model,"Target cited":o.target_domain_cited,"Target URLs":", ".join(o.target_urls_cited),"Competitors cited":", ".join(sorted({c.domain for c in o.citations if c.competitor})),"Other sources":", ".join(sorted({c.domain for c in o.citations if not c.is_target and not c.competitor})),"State":o.state.value,"Observed at":o.observed_at} for o in capable]);source_frame=pd.DataFrame([x.model_dump(mode="json") for x in sources]);stability_items=service.stability(history);stability=pd.DataFrame([x.model_dump(mode="json") for x in stability_items]);targets=pd.DataFrame([{"Prompt":o.prompt,"Provider":o.provider,"Model":o.model,"Target domain":next((c.domain for c in o.citations if c.is_target),""),"Target URL":c.normalized_url or c.url,"Citation order":c.index,"Observed at":o.observed_at} for o in capable for c in o.citations if c.is_target]);competitor=pd.DataFrame([{"Prompt":o.prompt,"Provider":o.provider,"Model":o.model,"Competitor domain":c.domain,"Citation URL":c.normalized_url or c.url,"Citation order":c.index,"Observed at":o.observed_at} for o in capable for c in o.citations if c.competitor]);history_frame=pd.DataFrame([{"Prompt":o.prompt,"Provider":o.provider,"Model":o.model,"State":service.history_state([x for x in capable if x.prompt==o.prompt and x.provider==o.provider and x.model==o.model]).value,"Target cited":o.target_domain_cited,"Observed at":o.observed_at,"Sample size":next((x.sample_size for x in stability_items if x.prompt==o.prompt and x.provider==o.provider and x.model==o.model),1)} for o in capable]);pages=[]
 if workflow is not None and target_domain and hasattr(workflow,"page_intelligence"):
  try:pages=run(workflow.page_intelligence(target_domain))
  except Exception:pages=[]
 page_frame=pd.DataFrame([x.model_dump(mode="json") for x in pages]);provider_frame=pd.DataFrame([{"Provider":p,"Model":m,"Grounded observations":len(items),"Target citation coverage":sum(bool(x.target_domain_cited) for x in items)/len(items),"Source domains":len({c.domain for x in items for c in x.citations}),"Citation stability":sum(bool(x.target_domain_cited) for x in items)/len(items),"Sample size":len(items)} for (p,m),items in __import__('itertools').groupby(sorted(capable,key=lambda x:(x.provider,x.model)),key=lambda x:(x.provider,x.model)) for items in [list(items)]])
 mt,pt,stt,ht,agt=st.tabs(["Mentions","Grounded citations","Sources","History","AEO/GEO comparison"])
 with mt:st.dataframe(provider_frame,hide_index=True,width="stretch") if not provider_frame.empty else st.info("No grounded provider observations are persisted.")
 with pt:st.dataframe(prompts,hide_index=True,width="stretch") if not prompts.empty else st.info("No successful citation-capable observations are persisted.");st.dataframe(page_frame,hide_index=True,width="stretch") if not page_frame.empty else st.info("Target-page enrichment is available after entering a compatible target domain.")
 with stt:st.dataframe(source_frame,hide_index=True,width="stretch") if not source_frame.empty else st.info("No structured source domains are persisted.")
 with ht:st.dataframe(history_frame,hide_index=True,width="stretch") if not history_frame.empty else st.info("No citation history is available.");st.write("Citation stability is provider/model/prompt specific and always includes sample size.")
 with agt:st.dataframe(page_frame,hide_index=True,width="stretch") if not page_frame.empty else st.info("No compatible AEO/GEO page evidence is available.");st.write("Readiness does not guarantee observed citation.")
 actions=service.actions(history)
 with st.container(horizontal=True):st.download_button("Target citations CSV",targets.to_csv(index=False),"target_citations.csv","text/csv");st.download_button("Competitor citations CSV",competitor.to_csv(index=False),"competitor_citations.csv","text/csv");st.download_button("Citation history CSV",history_frame.to_csv(index=False),"citation_history.csv","text/csv");st.download_button("Source domains CSV",source_frame.to_csv(index=False),"source_domains.csv","text/csv");st.download_button("Grounded report",grounded_markdown(coverage,sources,pages,actions),"grounded_citation_report.md","text/markdown")
def render_ai_visibility(workflow=None):
 workflow=workflow or AIVisibilityDashboardWorkflow();st.subheader("AI Visibility Monitoring");st.caption("Observed brand, competitor, and source visibility across configured AI provider APIs.");st.warning("AI responses are nondeterministic and provider/model specific. These observations do not represent universal AI rankings.");st.session_state.setdefault("ai_visibility_report",None)
 try:capabilities=run(workflow.providers());prompts=run(workflow.prompts());candidates=run(workflow.candidates())
 except Exception:capabilities=[];prompts=[];candidates=[]
 with st.form("ai-visibility-prompt",border=True):new_prompt=st.text_input("Add monitoring prompt",max_chars=4000);add=st.form_submit_button("Add prompt")
 if add and new_prompt:
  try:run(workflow.add_prompt(new_prompt));st.success("Monitoring prompt added. No provider call was made.")
  except Exception:st.error("The prompt could not be added.")
 if candidates:
  with st.form("ai-visibility-evidence-import",border=True):candidate=st.selectbox("Persisted evidence candidate",candidates,format_func=lambda x:f"{x[2]} · {x[0]} · {x[1]}");promote=st.form_submit_button("Add evidence prompt")
  if promote:
   try:run(workflow.promote_candidates((candidate,))) if hasattr(workflow,"promote_candidates") else run(workflow.add_prompt(candidate[2]));st.success("Persisted evidence promoted explicitly. No provider call was made.")
   except Exception:st.error("The evidence candidate could not be promoted.")
 if not capabilities:st.info("No supported AI response provider is configured. Persisted prompts and history remain available; monitoring calls are disabled.")
 labels=[f"{p.provider} · {p.model} · {p.classification.value}" for p in capabilities]
 with st.form("ai-visibility-run",border=True):
  brand=st.text_input("Target brand");domain=st.text_input("Target domain");aliases=st.text_input("Brand aliases",help="Comma-separated explicit aliases.");competitors=st.text_area("Competitors",help="One per line: Name=domain");chosen_prompts=st.multiselect("Monitored prompts",prompts,format_func=lambda p:p.text);chosen_providers=st.multiselect("Providers",labels,default=labels);repetitions=st.number_input("Repetitions",1,3,1);calls=len(chosen_prompts)*len(chosen_providers)*int(repetitions);st.caption(f"Prompts: {len(chosen_prompts)} · Providers: {len(chosen_providers)} · Repetitions: {int(repetitions)} · Total API calls: {calls}");submitted=st.form_submit_button("Run monitoring",type="primary",disabled=not capabilities)
 if submitted:
  try:
   comps={};
   for line in competitors.splitlines():
    if "=" in line:name,value=line.split("=",1);comps[name.strip()]=(value.strip(),)
   requests=[VisibilityRequest(prompt=p,brand_name=brand,brand_aliases=tuple(x.strip() for x in aliases.split(",") if x.strip()),target_domain=domain,competitors=comps) for p in chosen_prompts];provider_names=[capabilities[labels.index(x)].provider for x in chosen_providers];st.session_state.ai_visibility_report=run(workflow.run(requests,int(repetitions),provider_names))
  except Exception:st.error("Monitoring could not be completed. Provider failures are not recorded as brand absence.")
 report=st.session_state.ai_visibility_report
 history=run(workflow.history());history_frame=pd.DataFrame([{"Prompt":o.prompt,"Provider":o.provider,"Model":o.model,"Brand mentioned":o.brand_mention is not None if o.state.value=="SUCCESS" else None,"Target cited":o.target_domain_cited,"State":o.state.value,"Observed at":o.observed_at} for o in history])
 render_grounded(history,workflow,domain)
 if not isinstance(report,VisibilityReport):
  st.info("Add or select prompts, review the API-call preview, then run monitoring explicitly. No provider call occurs on rerender.")
  if not history_frame.empty:st.subheader("Persisted observation history");st.dataframe(history_frame,hide_index=True,width="stretch")
  return
 with st.container(horizontal=True):st.metric("Monitored prompts",report.run.prompt_count,border=True);st.metric("Brand mention coverage",f"{report.brand_mention_coverage:.1%}",border=True);st.metric("Citation coverage",f"{report.citation_coverage:.1%}" if report.citation_coverage is not None else "NOT AVAILABLE",border=True);st.metric("Competitors observed",report.competitors_observed,border=True);st.metric("Target domain citations",report.target_domain_citations,border=True)
 obs=observations_frame(report);providers=pd.DataFrame([x.model_dump(mode="json") for x in report.provider_summaries]);competitor=pd.DataFrame([{"Competitor":m.name,"Prompt":o.prompt,"Provider":o.provider,"Mention order":m.mention_order} for o in report.run.observations for m in o.competitor_mentions]);sources=pd.DataFrame([{"Domain":c.domain,"URL":c.url,"Provider":o.provider,"Classification":"Target" if c.is_target else "Competitor" if c.competitor else "Other"} for o in report.run.observations for c in o.citations]);pt,ot,ct,stt,dt=st.tabs(["Provider breakdown","Prompt observations","Competitors","Structured citations","Prompt detail"])
 with pt:st.dataframe(providers,hide_index=True,width="stretch")
 with ot:st.dataframe(obs,hide_index=True,width="stretch")
 with ct:st.dataframe(competitor,hide_index=True,width="stretch")
 with stt:st.dataframe(sources,hide_index=True,width="stretch") if not sources.empty else st.info("Structured citation tracking is not available in these observations.")
 with dt:
  selected=st.selectbox("Observation",report.run.observations,format_func=lambda o:f"{o.provider} · {o.prompt}");st.write(selected.response_text or "No successful response text.");st.caption(f"Grounding classification: {selected.classification.value} · State: {selected.state.value}")
 st.subheader("History");st.dataframe(history_frame,hide_index=True,width="stretch")
 with st.container(horizontal=True):st.download_button("Export observations CSV",obs.to_csv(index=False),"ai_visibility_observations.csv","text/csv");st.download_button("Export providers CSV",providers.to_csv(index=False),"ai_visibility_providers.csv","text/csv");st.download_button("Export competitors CSV",competitor.to_csv(index=False),"ai_visibility_competitors.csv","text/csv");st.download_button("Export citations CSV",sources.to_csv(index=False),"ai_visibility_citations.csv","text/csv");st.download_button("Export history CSV",history_frame.to_csv(index=False),"ai_visibility_history.csv","text/csv");st.download_button("Export Markdown",markdown(report),"ai_visibility_report.md","text/markdown")
